sample_file: samples.csv

absolute_path: /media/nadine/InternalMaybe/IntegrateALL

# Memory settings (in MB)
star_mem: 50000
fusioncatcher_mem: 64000  # High memory allocation for performance on cluster (64GB)
arriba_mem: 32000  # High memory allocation for Arriba fusion detection (32GB)
arriba_draw_mem: 16000  # Memory for Arriba visualization

# CPU settings  
threads: 4
fusioncatcher_threads: 8  # More threads for FusionCatcher performance
arriba_threads: 6  # Optimized threading for Arriba fusion detection

# GATK settings
gatk_mem: 32000  # High memory allocation for GATK variant calling (32GB)
gatk_java_opts: "-Xmx30g -XX:+UseParallelGC -XX:ParallelGCThreads=4"
picard_mem: 16000  # Memory for Picard preprocessing (16GB)

# RNAseqCNV settings
rnaseqcnv_mem: 24000  # High memory allocation for CNV analysis (24GB)
rnaseqcnv_threads: 6  # Optimized threading for R-based analysis
