sample_file: samples.csv

star_ref: /path/to/your/STAR_indexfiles/GRCh38.primary_assembly.genome.fa
star_gtf: /path/to/your/STAR_indexfiles/gencode.v32.annotation.gtf
star_mem: 80000
threads: 20
genome_index: /path/to/your/STAR/genome/index/directory
star_tmp_directory: /path/to/your/tmp/directory/STAR_tmp

ctat_input_directory: /path/to/your/data/sample/fastq_files
genome_lib: /media/nadine/HOME/nadine/ctat-mutations_test/ctat_genome_lib_build_dir

# singularity
use-singularity: True
latency-wait: 60
