sample_file: samples.csv
#counts: data/combined_counts/UKSH_counts.tsv
#combined_count_directory: data/combined_counts/
#single_counts_directory: data/single_counts/


rna_fusion_data_directory: /media/nadine/HOME/nadine/fusioncatcher/data/human_v102

star_ref: /media/nadine/HOME/nadine/STAR_indexfiles/GRCh38.primary_assembly.genome.fa
star_gtf: /media/nadine/HOME/nadine/STAR_indexfiles/gencode.v32.annotation.gtf
star_mem: 80000
threads: 20
genome_index: /media/nadine/HOME/nadine/STAR/ensembl_94_100
star_tmp_directory: /media/nadine/HOME/nadine/STAR_tmp


ctat_input_directory: /media/nadine/Alina/Blast-o-Matic-Fusioninator/data/samples
#ctat_output_dir: /media/nadine/Alina/Blast-o-Matic-Fusioninator/ctat_output_directory/ #works
genome_lib: /media/nadine/HOME/nadine/ctat-mutations_test/ctat_genome_lib_build_dir

# singularity
use-singularity: True

latency-wait: 60
