sample_file: samples.csv
counts: data/combined_counts/UKSH_counts.tsv
combined_count_directory: data/combined_counts/
single_counts_directory: data/single_counts/
sample_id: 21Ord12062


star_ref: /media/nadine/HOME/nadine/STAR_indexfiles/GRCh38.primary_assembly.genome.fa
star_gtf: /media/nadine/HOME/nadine/STAR_indexfiles/gencode.v32.annotation.gtf
star_mem: 80000
threads: 20
genome_index: /media/nadine/HOME/nadine/STAR/ensembl_94_100
star_tmp_directory: /media/nadine/HOME/nadine/STAR_tmp

samples:
  reads_left: data/samples/reads_1.fq.gz
  reads_right: data/samples/reads_2.fq.gz
  testReads_left: data/samples/test-reads-A01_R1_001.fastq.gz
  testReads_right: data/samples/test-reads-A01_R2_001.fastq.gz

#fastq_directory: /media/nadine/HOME/nadine/fastq
reads_per_gene_directory: data/reads_per_gene

#right_samples: [data/samples/reads_2.fq.gz,data/samples/test-reads-A01_R1_001.fastq.gz]
#right_samples: [data/samples/reads_2.fq.gz,data/samples/test-reads-A01_R2_001.fastq.gz]
right_samples: data/samples/reads_1.fq.gz
left_samples: data/samples/reads_2.fq.gz

test_sample: data/samples/reads_1.fq.gz data/samples/reads_2.fq.gz

#star_samples:
#  reads: data/samples/reads_1.fq.gz data/samples/reads_2.fq.gz
  #test_reads: data/samples/test-reads-A01_R1_001.fastq.gz data/samples/test-reads-A01_R2_001.fastq.gz

#STAR_left_samples: data/samples/I29799-L1_S33_L001_R1_001.fastq.gz
#STAR_right_samples: data/samples/I29799-L1_S33_L001_R2_001.fastq.gz


ctat_mount_dir: /home/nadine/PycharmProjects/Blast-o-Matic-Fusioninator/data/samples  # works
ctat_input_directory: /media/nadine/Alina/Blast-o-Matic-Fusioninator/data/samples
ctat_output_dir: /home/nadine/PycharmProjects/Blast-o-Matic-Fusioninator #works
#ctat_output_dir: /media/nadine/Alina/Blast-o-Matic-Fusioninator/ctat_output_directory #doesn't work yet
genome_lib: /media/nadine/HOME/nadine/ctat-mutations_test/ctat_genome_lib_build_dir
ctat_right_samples: /reads_2.fq.gz
ctat_left_samples: /reads_1.fq.gz

# singularity
use-singularity: True
#singularity-args: --bind /home/nadine/PycharmProjects/Blast-o-Matic-Fusioninator/data/samples

latency-wait: 60
