sample_file: samples.csv

absolute_path: /media/nadine/InternalMaybe/IntegrateALL

# Memory settings (in MB)
star_mem: 50000
fusioncatcher_mem: 32000  # High memory allocation for time-intensive job
arriba_mem: 16000
arriba_draw_mem: 8000
picard_mem: 8000
gatk_mem: 16000
vcf_mem: 4000

# CPU settings  
threads: 4
fusioncatcher_threads: 8  # More threads for FusionCatcher performance
arriba_threads: 4
vcf_threads: 4

# GATK settings
gatk_java_opts: "-XX:+UseParallelGC"
