sample_file: samples.csv

absolute_path: /path/to/IntegrateALL

# Memory settings (in MB)
star_mem: 50000
fusioncatcher_mem: 32000  # High memory allocation for time-intensive job
arriba_mem: 24000  # Enhanced memory for fusion detection performance
arriba_draw_mem: 12000  # Increased memory for fusion visualization
picard_mem: 16000  # Increased for BAM preprocessing performance
gatk_mem: 32000  # High memory allocation for GATK variant calling
vcf_mem: 16000
rnaseqcnv_mem: 20000  # High memory allocation for R-based CNV analysis

# CPU settings  
threads: 4
fusioncatcher_threads: 8  # More threads for FusionCatcher performance
arriba_threads: 6  # Optimized threading for fusion detection
vcf_threads: 8
rnaseqcnv_threads: 6  # Optimized threading for R-based analysis

# GATK settings
gatk_java_opts: "-XX:+UseParallelGC -XX:ParallelGCThreads=4"  # Optimized for multi-core performance
