channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  # Core tools - using latest compatible versions
  - arriba=2.4.0
  - bcftools>=1.19
  - gatk4>=4.5.0
  - htslib>=1.19
  - samtools>=1.19
  - star=2.7.11a
  - multiqc>=1.21
  
  # Python environment
  - python=3.11
  - numpy>=1.26.0
  - pandas>=2.2.0
  - pip>=24.0
  - scikit-learn>=1.5.0
  - scipy>=1.13.0
  - setuptools<81
  
  # R environment 
  - r-base=4.3
  
  # Bioconductor packages - let conda resolve versions
  - bioconductor-biobase
  - bioconductor-biocgenerics
  - bioconductor-biocparallel
  - bioconductor-biostrings
  - bioconductor-delayedarray
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-genomicalignments
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-matrixgenerics
  - bioconductor-rhtslib
  - bioconductor-rsamtools
  - bioconductor-s4vectors
  - bioconductor-summarizedexperiment
  - bioconductor-xvector
  - bioconductor-zlibbioc
  
  # Essential R packages - let conda resolve compatible versions
  - r-devtools
  - r-data.table
  - r-ggplot2
  - r-dplyr
  - r-readr
  - r-readxl
  - r-jsonlite
  - r-httr
  - r-curl
  - r-openssl
  - r-xml2
  - r-yaml
  - r-knitr
  - r-rmarkdown
  - r-circlize
  
  # System utilities
  - bwa=0.7.17
  - unzip>=6.0
  - wget>=1.21.0
  - openjdk>=11
  
  # Snakemake and workflow management
  - snakemake-minimal>=8.0
  
  # Python bioinformatics tools
  - pysamstats
  
  - pip:
      # Python packages that need to be installed via pip
      - argparse-dataclass>=2.0.0
      - snakemake-executor-plugin-slurm>=0.7.0
      - snakemake-executor-plugin-slurm-jobstep>=0.2.1
